<?php

namespace AppBundle\Repository;

/**
 * ArtikelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtikelRepository extends \Doctrine\ORM\EntityRepository
{
}
