<?php

namespace AppBundle\Repository;

/**
 * Coefficient_yRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Coefficient_yRepository extends \Doctrine\ORM\EntityRepository
{
}
