<?php

namespace AppBundle\Repository;

/**
 * Coefficient_iRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Coefficient_iRepository extends \Doctrine\ORM\EntityRepository
{
}
