<?php

namespace AppBundle\Repository;

/**
 * Coefficient_qRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Coefficient_qRepository extends \Doctrine\ORM\EntityRepository
{
}
