<?php

namespace AppBundle\Repository;

/**
 * GambarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GambarRepository extends \Doctrine\ORM\EntityRepository
{
}
