<?php

namespace AppBundle\Repository;

/**
 * KataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KataRepository extends \Doctrine\ORM\EntityRepository
{
}
